# /base.yml
theme:
  name: material
  features:
#    - navigation.tabs
    - navigation.expand
  palette:
    - scheme: default
      primary: custom

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format